language: generic

git:
  depth: false

os: linux
dist: focal

script:
  - mkdir src/main/scripts/bin
  - cd src/main/scripts/win64
  - chmod 777 build.sh
  - ./build.sh
  - cd ../linux64
  - chmod 777 build.sh
  - ./build.sh

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file:
    - "src/main/scripts/bin/libcontroller-sdl.dll"
    - "src/main/scripts/bin/libcontroller-sdl.so"
  skip_cleanup: true
