language: generic

git:
  depth: false

os: linux
dist: jammy

script:
  - cd src/main/scripts/win64
  - mkdir bin/win64
  - chmod 777 build.sh
  - ./build.sh

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file:
    - "bin/win64/libcontroller-sdl.dll"
  skip_cleanup: true
  on:
    branches:
      only:
        - master