language: generic

git:
  depth: false

os: linux
dist: focal

script:
  - cd src/main/scripts/win64
  - mkdir bin
  - chmod 777 build.sh
  - ./build.sh
  - cd ../linux64
  - mkdir bin
  - chmod 777 build.sh
  - ./build.sh

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file:
    - "src/main/scripts/win64/bin/libcontroller-sdl.dll"
    - "src/main/scripts/linux64/bin/libcontroller-sdl.so"
  skip_cleanup: true
  on:
    branches:
      only:
        - master
